package com.cba.core.wiremeweb.model;
// Generated Jun 20, 2023 2:49:48 PM by Hibernate Tools 4.3.1


import jakarta.persistence.*;

import java.util.Date;

/**
 * ApplicationSignature generated by hbm2java
 */
@Entity
@Table(name = "application_signature"
)
public class ApplicationSignature implements java.io.Serializable {

    private Integer id;
    private String appVersion;
    private String appSignature;
    private String packagefileSignature;
    private Integer sysfileSize;
    private Date createdAt;

    public ApplicationSignature() {
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "app_version", nullable = false, length = 10)
    public String getAppVersion() {
        return this.appVersion;
    }

    public void setAppVersion(String appVersion) {
        this.appVersion = appVersion;
    }

    @Column(name = "app_signature", nullable = false, length = 65535, columnDefinition = "TEXT")
    public String getAppSignature() {
        return this.appSignature;
    }

    public void setAppSignature(String appSignature) {
        this.appSignature = appSignature;
    }

    @Column(name = "packagefile_signature", nullable = false, length = 65535, columnDefinition = "TEXT")
    public String getPackagefileSignature() {
        return this.packagefileSignature;
    }

    public void setPackagefileSignature(String packagefileSignature) {
        this.packagefileSignature = packagefileSignature;
    }

    @Column(name = "sysfile_size")
    public Integer getSysfileSize() {
        return this.sysfileSize;
    }

    public void setSysfileSize(Integer sysfileSize) {
        this.sysfileSize = sysfileSize;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_at", length = 19)
    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

}


