package com.cba.core.wiremeweb.model;
// Generated Jun 20, 2023 2:49:48 PM by Hibernate Tools 4.3.1


import java.util.Date;

import jakarta.persistence.*;


/**
 * CardType generated by hbm2java
 */
@Entity
@Table(name = "card_type"
)
public class CardType implements java.io.Serializable {


    private String cardLabel;
    private Status status;
    private String description;
    private Date createdAt;
    private Date updatedAt;

    public CardType() {
    }


    public CardType(String cardLabel, Status status, Date createdAt, Date updatedAt) {
        this.cardLabel = cardLabel;
        this.status = status;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public CardType(String cardLabel, Status status, String description, Date createdAt, Date updatedAt) {
        this.cardLabel = cardLabel;
        this.status = status;
        this.description = description;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    @Id
    @Column(name = "card_label", unique = true, nullable = false, length = 100)
    public String getCardLabel() {
        return this.cardLabel;
    }

    public void setCardLabel(String cardLabel) {
        this.cardLabel = cardLabel;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "status", nullable = false)
    public Status getStatus() {
        return this.status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }


    @Column(name = "description", length = 100)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_at", nullable = false, length = 19)
    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_at", nullable = false, length = 19)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }


}


