package com.cba.core.wiremeweb.model;
// Generated Jun 20, 2023 2:49:48 PM by Hibernate Tools 4.3.1


import jakarta.persistence.*;

import java.util.HashSet;
import java.util.Set;


/**
 * ConsumingService generated by hbm2java
 */
@Entity
@Table(name = "consuming_service"
)
public class ConsumingService implements java.io.Serializable {


    private Integer id;
    private String serviceName;
    private Set<Subscription> subscriptions = new HashSet<Subscription>(0);

    public ConsumingService() {
    }


    public ConsumingService(String serviceName) {
        this.serviceName = serviceName;
    }

    public ConsumingService(String serviceName, Set<Subscription> subscriptions) {
        this.serviceName = serviceName;
        this.subscriptions = subscriptions;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }


    @Column(name = "service_name", nullable = false)
    public String getServiceName() {
        return this.serviceName;
    }

    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "consumingService")
    public Set<Subscription> getSubscriptions() {
        return this.subscriptions;
    }

    public void setSubscriptions(Set<Subscription> subscriptions) {
        this.subscriptions = subscriptions;
    }


}


