package com.cba.core.wiremeweb.model;
// Generated Jun 20, 2023 2:49:48 PM by Hibernate Tools 4.3.1


import jakarta.persistence.*;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.util.Date;


/**
 * DeviceConfig generated by hbm2java
 */
@Entity
@Table(name = "device_config"
)
@EntityListeners(AuditingEntityListener.class) // enable entity level auditing for create,modified attributes
public class DeviceConfig implements java.io.Serializable {

    private int id;
    private Device device;
    private Status status;
    @LastModifiedBy
    private String userByModifiedBy;
    @CreatedBy
    private String userByCreatedBy;
    private String configType;
    private String config;
    @CreatedDate
    private Date createdAt;
    @LastModifiedDate
    private Date updatedAt;

    public DeviceConfig() {
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "device_id", nullable = false)
    public Device getDevice() {
        return this.device;
    }

    public void setDevice(Device device) {
        this.device = device;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "status", nullable = false)
    public Status getStatus() {
        return this.status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    @Column(name = "modified_by", length = 45)
    public String getUserByModifiedBy() {
        return this.userByModifiedBy;
    }

    public void setUserByModifiedBy(String userByModifiedBy) {
        this.userByModifiedBy = userByModifiedBy;
    }

    @Column(name = "created_by", nullable = false, length = 45)
    public String getUserByCreatedBy() {
        return this.userByCreatedBy;
    }

    public void setUserByCreatedBy(String userByCreatedBy) {
        this.userByCreatedBy = userByCreatedBy;
    }

    @Column(name = "config_type", nullable = false, length = 30)
    public String getConfigType() {
        return this.configType;
    }

    public void setConfigType(String configType) {
        this.configType = configType;
    }

    @Column(name = "config", nullable = false, length = 65535, columnDefinition = "TEXT")
    public String getConfig() {
        return this.config;
    }

    public void setConfig(String config) {
        this.config = config;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_at", nullable = false, length = 19)
    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_at", nullable = false, length = 19)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

}


