package com.cba.core.wiremeweb.model;
// Generated Nov 27, 2023 1:02:15 PM by Hibernate Tools 4.3.1


import jakarta.persistence.*;

/**
 * District generated by hbm2java
 */
@Entity
@Table(name = "district")
public class District implements java.io.Serializable {

    private String code;
    private Province province;
    private String description;
    private Float lat;
    private Float lon;

    public District() {
    }

    public District(String code, Province province) {
        this.code = code;
        this.province = province;
    }

    public District(String code, Province province, String description, Float lat, Float lon) {
        this.code = code;
        this.province = province;
        this.description = description;
        this.lat = lat;
        this.lon = lon;
    }

    @Id
    @Column(name = "code", unique = true, nullable = false, length = 20)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "province", nullable = false)
    public Province getProvince() {
        return this.province;
    }

    public void setProvince(Province province) {
        this.province = province;
    }

    @Column(name = "description", length = 100)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "lat", precision = 12, scale = 0)
    public Float getLat() {
        return this.lat;
    }

    public void setLat(Float lat) {
        this.lat = lat;
    }

    @Column(name = "lon", precision = 12, scale = 0)
    public Float getLon() {
        return this.lon;
    }

    public void setLon(Float lon) {
        this.lon = lon;
    }

}


