package com.cba.core.wiremeweb.model;
// Generated Jun 20, 2023 2:49:48 PM by Hibernate Tools 4.3.1


import jakarta.persistence.*;


/**
 * FailedSubmission generated by hbm2java
 */
@Entity
@Table(name = "failed_submission"
)
public class FailedSubmission implements java.io.Serializable {


    private int id;
    private Subscription subscription;
    private int currentRetry;
    private String record;
    private String resource;
    private String event;
    private String cause;

    public FailedSubmission() {
    }


    public FailedSubmission(int id, int currentRetry, String record, String resource, String event, String cause) {
        this.id = id;
        this.currentRetry = currentRetry;
        this.record = record;
        this.resource = resource;
        this.event = event;
        this.cause = cause;
    }

    public FailedSubmission(int id, Subscription subscription, int currentRetry, String record, String resource, String event, String cause) {
        this.id = id;
        this.subscription = subscription;
        this.currentRetry = currentRetry;
        this.record = record;
        this.resource = resource;
        this.event = event;
        this.cause = cause;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "subscription_id")
    public Subscription getSubscription() {
        return this.subscription;
    }

    public void setSubscription(Subscription subscription) {
        this.subscription = subscription;
    }


    @Column(name = "current_retry", nullable = false)
    public int getCurrentRetry() {
        return this.currentRetry;
    }

    public void setCurrentRetry(int currentRetry) {
        this.currentRetry = currentRetry;
    }


    @Column(name = "record", nullable = false, length = 65535, columnDefinition = "TEXT")
    public String getRecord() {
        return this.record;
    }

    public void setRecord(String record) {
        this.record = record;
    }


    @Column(name = "resource", nullable = false, length = 20)
    public String getResource() {
        return this.resource;
    }

    public void setResource(String resource) {
        this.resource = resource;
    }


    @Column(name = "event", nullable = false, length = 20)
    public String getEvent() {
        return this.event;
    }

    public void setEvent(String event) {
        this.event = event;
    }


    @Column(name = "cause", nullable = false, length = 20)
    public String getCause() {
        return this.cause;
    }

    public void setCause(String cause) {
        this.cause = cause;
    }


}


