package com.cba.core.wiremeweb.model;
// Generated Jun 20, 2023 2:49:48 PM by Hibernate Tools 4.3.1


import jakarta.persistence.*;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Merchant generated by hbm2java
 */
@Entity
@Table(name = "merchant"
)
public class Merchant implements java.io.Serializable {


    private Integer id;
    private Bank bank;
    private MerchantCustomer merchantCustomer;
    private Status status;
    private User userByCreatedBy;
    private User userByModifiedBy;
    private String name;
    private String merchantId;
    private String email;
    private String contactNo;
    private String province;
    private String district;
    private Date createdAt;
    private Date updatedAt;
    private Set<Terminal> terminals = new HashSet<Terminal>(0);
    private Set<User> users = new HashSet<User>(0);

    public Merchant() {
    }

    public Merchant(Integer id) {
        this.id = id;
    }

    public Merchant(MerchantCustomer merchantCustomer, User userByCreatedBy, String name, String merchantId, String email, String province, String district, Date createdAt, Date updatedAt) {
        this.merchantCustomer = merchantCustomer;
        this.userByCreatedBy = userByCreatedBy;
        this.name = name;
        this.merchantId = merchantId;
        this.email = email;
        this.province = province;
        this.district = district;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Merchant(Bank bank, MerchantCustomer merchantCustomer, Status status, User userByCreatedBy, User userByModifiedBy, String name, String merchantId, String email, String contactNo, String province, String district, Date createdAt, Date updatedAt, Set<Terminal> terminals, Set<User> users) {
        this.bank = bank;
        this.merchantCustomer = merchantCustomer;
        this.status = status;
        this.userByCreatedBy = userByCreatedBy;
        this.userByModifiedBy = userByModifiedBy;
        this.name = name;
        this.merchantId = merchantId;
        this.email = email;
        this.contactNo = contactNo;
        this.province = province;
        this.district = district;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.terminals = terminals;
        this.users = users;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "bank")
    public Bank getBank() {
        return this.bank;
    }

    public void setBank(Bank bank) {
        this.bank = bank;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "merchant_customer_id", nullable = false)
    public MerchantCustomer getMerchantCustomer() {
        return this.merchantCustomer;
    }

    public void setMerchantCustomer(MerchantCustomer merchantCustomer) {
        this.merchantCustomer = merchantCustomer;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "status")
    public Status getStatus() {
        return this.status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by", nullable = false)
    public User getUserByCreatedBy() {
        return this.userByCreatedBy;
    }

    public void setUserByCreatedBy(User userByCreatedBy) {
        this.userByCreatedBy = userByCreatedBy;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "modified_by")
    public User getUserByModifiedBy() {
        return this.userByModifiedBy;
    }

    public void setUserByModifiedBy(User userByModifiedBy) {
        this.userByModifiedBy = userByModifiedBy;
    }


    @Column(name = "name", nullable = false, length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }


    @Column(name = "merchant_id", nullable = false, length = 16)
    public String getMerchantId() {
        return this.merchantId;
    }

    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId;
    }


    @Column(name = "email", nullable = false, length = 40)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }


    @Column(name = "contact_no", length = 15)
    public String getContactNo() {
        return this.contactNo;
    }

    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }


    @Column(name = "province", nullable = false, length = 30)
    public String getProvince() {
        return this.province;
    }

    public void setProvince(String province) {
        this.province = province;
    }


    @Column(name = "district", nullable = false, length = 30)
    public String getDistrict() {
        return this.district;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_at", nullable = false, length = 19)
    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_at", nullable = false, length = 19)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
    public Set<Terminal> getTerminals() {
        return this.terminals;
    }

    public void setTerminals(Set<Terminal> terminals) {
        this.terminals = terminals;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
    public Set<User> getUsers() {
        return this.users;
    }

    public void setUsers(Set<User> users) {
        this.users = users;
    }


}


