package com.cba.core.wiremeweb.model;
// Generated Nov 27, 2023 1:02:15 PM by Hibernate Tools 4.3.1


import jakarta.persistence.*;

import java.util.HashSet;
import java.util.Set;

/**
 * Province generated by hbm2java
 */
@Entity
@Table(name = "province")
public class Province implements java.io.Serializable {

    private String code;
    private String description;
    private Set<District> districts = new HashSet<District>(0);

    public Province() {
    }

    public Province(String code) {
        this.code = code;
    }

    public Province(String code, String description, Set<District> districts) {
        this.code = code;
        this.description = description;
        this.districts = districts;
    }

    @Id
    @Column(name = "code", unique = true, nullable = false, length = 20)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "description", length = 100)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "province")
    public Set<District> getDistricts() {
        return this.districts;
    }

    public void setDistricts(Set<District> districts) {
        this.districts = districts;
    }

}


