package com.cba.core.wiremeweb.model;
// Generated Jun 20, 2023 2:49:48 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.*;


/**
 * Resource generated by hbm2java
 */
@Entity
@Table(name = "resource"
)
public class Resource implements java.io.Serializable {


    private Integer id;
    private String name;
    private Date createdAt;
    private Date updatedAt;
    private Set<Subscription> subscriptions = new HashSet<Subscription>(0);
    private Set<Permission> permissions = new HashSet<Permission>(0);

    public Resource() {
    }


    public Resource(Date createdAt, Date updatedAt) {
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Resource(String name, Date createdAt, Date updatedAt, Set<Subscription> subscriptions, Set<Permission> permissions) {
        this.name = name;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.subscriptions = subscriptions;
        this.permissions = permissions;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }


    @Column(name = "name", length = 20)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_at", nullable = false, length = 19)
    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_at", nullable = false, length = 19)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "subscription_resource", catalog = "haradb_new", joinColumns = {
            @JoinColumn(name = "resourceid", nullable = false, updatable = false)}, inverseJoinColumns = {
            @JoinColumn(name = "subscriptionid", nullable = false, updatable = false)})
    public Set<Subscription> getSubscriptions() {
        return this.subscriptions;
    }

    public void setSubscriptions(Set<Subscription> subscriptions) {
        this.subscriptions = subscriptions;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "resource")
    public Set<Permission> getPermissions() {
        return this.permissions;
    }

    public void setPermissions(Set<Permission> permissions) {
        this.permissions = permissions;
    }


}


