package com.cba.core.wiremeweb.model;
// Generated Jun 20, 2023 2:49:48 PM by Hibernate Tools 4.3.1


import jakarta.persistence.*;

import java.util.Date;


/**
 * SettlementInfo generated by hbm2java
 */
@Entity
@Table(name = "settlement_info"
)
public class SettlementInfo implements java.io.Serializable {


    private Long id;
    private Status status;
    private Terminal terminal;
    private TransactionCore transactionCore;
    private long batchId;
    private Date dateTime;

    public SettlementInfo() {
    }

    public SettlementInfo(Status status, Terminal terminal, TransactionCore transactionCore, long batchId, Date dateTime) {
        this.status = status;
        this.terminal = terminal;
        this.transactionCore = transactionCore;
        this.batchId = batchId;
        this.dateTime = dateTime;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "status", nullable = false)
    public Status getStatus() {
        return this.status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "terminal_id", nullable = false)
    public Terminal getTerminal() {
        return this.terminal;
    }

    public void setTerminal(Terminal terminal) {
        this.terminal = terminal;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tran_id", nullable = false)
    public TransactionCore getTransactionCore() {
        return this.transactionCore;
    }

    public void setTransactionCore(TransactionCore transactionCore) {
        this.transactionCore = transactionCore;
    }


    @Column(name = "batch_id", nullable = false)
    public long getBatchId() {
        return this.batchId;
    }

    public void setBatchId(long batchId) {
        this.batchId = batchId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date_time", nullable = false, length = 19)
    public Date getDateTime() {
        return this.dateTime;
    }

    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }


}


