package com.cba.core.wiremeweb.model;
// Generated Jun 20, 2023 2:49:48 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.*;


/**
 * Subscription generated by hbm2java
 */
@Entity
@Table(name = "subscription"
)
public class Subscription implements java.io.Serializable {


    private Integer id;
    private ConsumingService consumingService;
    private String callbackurl;
    private int retrycount;
    private String mailonsuccess;
    private String mailonfaliure;
    private Set<FailedSubmission> failedSubmissions = new HashSet<FailedSubmission>(0);
    private Set<Resource> resources = new HashSet<Resource>(0);

    public Subscription() {
    }


    public Subscription(String callbackurl, int retrycount) {
        this.callbackurl = callbackurl;
        this.retrycount = retrycount;
    }

    public Subscription(ConsumingService consumingService, String callbackurl, int retrycount, String mailonsuccess, String mailonfaliure, Set<FailedSubmission> failedSubmissions, Set<Resource> resources) {
        this.consumingService = consumingService;
        this.callbackurl = callbackurl;
        this.retrycount = retrycount;
        this.mailonsuccess = mailonsuccess;
        this.mailonfaliure = mailonfaliure;
        this.failedSubmissions = failedSubmissions;
        this.resources = resources;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "consumingserviceid")
    public ConsumingService getConsumingService() {
        return this.consumingService;
    }

    public void setConsumingService(ConsumingService consumingService) {
        this.consumingService = consumingService;
    }


    @Column(name = "callbackurl", nullable = false, length = 65535, columnDefinition = "TEXT")
    public String getCallbackurl() {
        return this.callbackurl;
    }

    public void setCallbackurl(String callbackurl) {
        this.callbackurl = callbackurl;
    }


    @Column(name = "retrycount", nullable = false)
    public int getRetrycount() {
        return this.retrycount;
    }

    public void setRetrycount(int retrycount) {
        this.retrycount = retrycount;
    }


    @Column(name = "mailonsuccess", length = 65535, columnDefinition = "TEXT")
    public String getMailonsuccess() {
        return this.mailonsuccess;
    }

    public void setMailonsuccess(String mailonsuccess) {
        this.mailonsuccess = mailonsuccess;
    }


    @Column(name = "mailonfaliure", length = 65535, columnDefinition = "TEXT")
    public String getMailonfaliure() {
        return this.mailonfaliure;
    }

    public void setMailonfaliure(String mailonfaliure) {
        this.mailonfaliure = mailonfaliure;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "subscription")
    public Set<FailedSubmission> getFailedSubmissions() {
        return this.failedSubmissions;
    }

    public void setFailedSubmissions(Set<FailedSubmission> failedSubmissions) {
        this.failedSubmissions = failedSubmissions;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "subscription_resource", catalog = "haradb_new", joinColumns = {
            @JoinColumn(name = "subscriptionid", nullable = false, updatable = false)}, inverseJoinColumns = {
            @JoinColumn(name = "resourceid", nullable = false, updatable = false)})
    public Set<Resource> getResources() {
        return this.resources;
    }

    public void setResources(Set<Resource> resources) {
        this.resources = resources;
    }


}


