package com.cba.core.wiremeweb.model;
// Generated Jun 20, 2023 2:49:48 PM by Hibernate Tools 4.3.1


import jakarta.persistence.*;

import java.time.Instant;


/**
 * RefreshToken generated by hbm2java
 */
@Entity
@Table(name = "token_refresh"
        , uniqueConstraints = @UniqueConstraint(columnNames = "token")
)
public class TokenRefresh implements java.io.Serializable {


    private Integer id;
    private User user;
    private Instant expiryDate;
    private String token;

    public TokenRefresh() {
    }


    public TokenRefresh(Instant expiryDate, String token) {
        this.expiryDate = expiryDate;
        this.token = token;
    }

    public TokenRefresh(User user, Instant expiryDate, String token) {
        this.user = user;
        this.expiryDate = expiryDate;
        this.token = token;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "expiry_date", nullable = false, length = 26)
    public Instant getExpiryDate() {
        return this.expiryDate;
    }

    public void setExpiryDate(Instant expiryDate) {
        this.expiryDate = expiryDate;
    }


    @Column(name = "token", unique = true, nullable = false)
    public String getToken() {
        return this.token;
    }

    public void setToken(String token) {
        this.token = token;
    }


}


