package com.cba.core.wiremeweb.model;
// Generated Jun 20, 2023 2:49:48 PM by Hibernate Tools 4.3.1


import java.util.Date;

import jakarta.persistence.*;


/**
 * TransactionSwitch generated by hbm2java
 */
@Entity
@Table(name = "transaction_switch"
)
public class TransactionSwitch implements java.io.Serializable {


    private Long id;
    private Bank bank;
    private Status status;
    private TransactionType transactionType;
    private String sessionId;
    private String mti;
    private String pan;
    private String processingCode;
    private String tranAmount;
    private String settleAmount;
    private String cardHolderBillAmount;
    private String transmissionDate;
    private String cardHolderBillingFeeAmount;
    private String conversionRateSettlement;
    private String conversionRateBilling;
    private String traceNo;
    private String localTranTime;
    private String localTranDate;
    private String expireDate;
    private String settlementDate;
    private String currencyConversionDate;
    private String captureDate;
    private String merchantType;
    private String acqInstituteCountryCode;
    private String panExtCountryCode;
    private String fwdInstitiuteCountryCode;
    private String entryMode;
    private String panSeqNo;
    private String nii;
    private String conditionCode;
    private String captureCode;
    private String authIdLength;
    private String tranFee;
    private String settleFee;
    private String tranProcessingFee;
    private String settlementProcessingFee;
    private String acqInstituteIdCode;
    private String forwardInstituteIdCode;
    private String extPan;
    private String trackTwoData;
    private String trackThreeData;
    private String retrevalReferenceNo;
    private String authCode;
    private String responseCode;
    private String serviceRestrictionCode;
    private String terminalId;
    private String merchantId;
    private String cardAcceptanceLocation;
    private String adnitionalResponseData;
    private String field46;
    private String field47;
    private String field48;
    private String transactionCurrencyCode;
    private String trackOneData;
    private String settlementCurrencyCode;
    private String cardHolderBillingCurrencyCode;
    private String secRelatedInfo;
    private String additionAmount;
    private String emvData;
    private String field56;
    private String field57;
    private String field58;
    private String field59;
    private String field60;
    private String field61;
    private String field62;
    private String field63;
    private String macData;
    private boolean settlementStatus;
    private String cardLabel;
    private String serialNumber;
    private String imeiNumber;
    private Date createdAt;
    private Date updatedAt;

    public TransactionSwitch() {
    }


    public TransactionSwitch(TransactionType transactionType, String sessionId, String mti, String processingCode, String traceNo, String terminalId, boolean settlementStatus, String serialNumber, String imeiNumber, Date createdAt, Date updatedAt) {
        this.transactionType = transactionType;
        this.sessionId = sessionId;
        this.mti = mti;
        this.processingCode = processingCode;
        this.traceNo = traceNo;
        this.terminalId = terminalId;
        this.settlementStatus = settlementStatus;
        this.serialNumber = serialNumber;
        this.imeiNumber = imeiNumber;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public TransactionSwitch(Bank bank, Status status, TransactionType transactionType, String sessionId, String mti, String pan, String processingCode, String tranAmount, String settleAmount, String cardHolderBillAmount, String transmissionDate, String cardHolderBillingFeeAmount, String conversionRateSettlement, String conversionRateBilling, String traceNo, String localTranTime, String localTranDate, String expireDate, String settlementDate, String currencyConversionDate, String captureDate, String merchantType, String acqInstituteCountryCode, String panExtCountryCode, String fwdInstitiuteCountryCode, String entryMode, String panSeqNo, String nii, String conditionCode, String captureCode, String authIdLength, String tranFee, String settleFee, String tranProcessingFee, String settlementProcessingFee, String acqInstituteIdCode, String forwardInstituteIdCode, String extPan, String trackTwoData, String trackThreeData, String retrevalReferenceNo, String authCode, String responseCode, String serviceRestrictionCode, String terminalId, String merchantId, String cardAcceptanceLocation, String adnitionalResponseData, String field46, String field47, String field48, String transactionCurrencyCode, String trackOneData, String settlementCurrencyCode, String cardHolderBillingCurrencyCode, String secRelatedInfo, String additionAmount, String emvData, String field56, String field57, String field58, String field59, String field60, String field61, String field62, String field63, String macData, boolean settlementStatus, String cardLabel, String serialNumber, String imeiNumber, Date createdAt, Date updatedAt) {
        this.bank = bank;
        this.status = status;
        this.transactionType = transactionType;
        this.sessionId = sessionId;
        this.mti = mti;
        this.pan = pan;
        this.processingCode = processingCode;
        this.tranAmount = tranAmount;
        this.settleAmount = settleAmount;
        this.cardHolderBillAmount = cardHolderBillAmount;
        this.transmissionDate = transmissionDate;
        this.cardHolderBillingFeeAmount = cardHolderBillingFeeAmount;
        this.conversionRateSettlement = conversionRateSettlement;
        this.conversionRateBilling = conversionRateBilling;
        this.traceNo = traceNo;
        this.localTranTime = localTranTime;
        this.localTranDate = localTranDate;
        this.expireDate = expireDate;
        this.settlementDate = settlementDate;
        this.currencyConversionDate = currencyConversionDate;
        this.captureDate = captureDate;
        this.merchantType = merchantType;
        this.acqInstituteCountryCode = acqInstituteCountryCode;
        this.panExtCountryCode = panExtCountryCode;
        this.fwdInstitiuteCountryCode = fwdInstitiuteCountryCode;
        this.entryMode = entryMode;
        this.panSeqNo = panSeqNo;
        this.nii = nii;
        this.conditionCode = conditionCode;
        this.captureCode = captureCode;
        this.authIdLength = authIdLength;
        this.tranFee = tranFee;
        this.settleFee = settleFee;
        this.tranProcessingFee = tranProcessingFee;
        this.settlementProcessingFee = settlementProcessingFee;
        this.acqInstituteIdCode = acqInstituteIdCode;
        this.forwardInstituteIdCode = forwardInstituteIdCode;
        this.extPan = extPan;
        this.trackTwoData = trackTwoData;
        this.trackThreeData = trackThreeData;
        this.retrevalReferenceNo = retrevalReferenceNo;
        this.authCode = authCode;
        this.responseCode = responseCode;
        this.serviceRestrictionCode = serviceRestrictionCode;
        this.terminalId = terminalId;
        this.merchantId = merchantId;
        this.cardAcceptanceLocation = cardAcceptanceLocation;
        this.adnitionalResponseData = adnitionalResponseData;
        this.field46 = field46;
        this.field47 = field47;
        this.field48 = field48;
        this.transactionCurrencyCode = transactionCurrencyCode;
        this.trackOneData = trackOneData;
        this.settlementCurrencyCode = settlementCurrencyCode;
        this.cardHolderBillingCurrencyCode = cardHolderBillingCurrencyCode;
        this.secRelatedInfo = secRelatedInfo;
        this.additionAmount = additionAmount;
        this.emvData = emvData;
        this.field56 = field56;
        this.field57 = field57;
        this.field58 = field58;
        this.field59 = field59;
        this.field60 = field60;
        this.field61 = field61;
        this.field62 = field62;
        this.field63 = field63;
        this.macData = macData;
        this.settlementStatus = settlementStatus;
        this.cardLabel = cardLabel;
        this.serialNumber = serialNumber;
        this.imeiNumber = imeiNumber;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "bank")
    public Bank getBank() {
        return this.bank;
    }

    public void setBank(Bank bank) {
        this.bank = bank;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "status")
    public Status getStatus() {
        return this.status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tran_type", nullable = false)
    public TransactionType getTransactionType() {
        return this.transactionType;
    }

    public void setTransactionType(TransactionType transactionType) {
        this.transactionType = transactionType;
    }


    @Column(name = "session_id", nullable = false, length = 100)
    public String getSessionId() {
        return this.sessionId;
    }

    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }


    @Column(name = "mti", nullable = false, length = 4)
    public String getMti() {
        return this.mti;
    }

    public void setMti(String mti) {
        this.mti = mti;
    }


    @Column(name = "pan", length = 512)
    public String getPan() {
        return this.pan;
    }

    public void setPan(String pan) {
        this.pan = pan;
    }


    @Column(name = "processing_code", nullable = false, length = 6)
    public String getProcessingCode() {
        return this.processingCode;
    }

    public void setProcessingCode(String processingCode) {
        this.processingCode = processingCode;
    }


    @Column(name = "tran_amount", length = 12)
    public String getTranAmount() {
        return this.tranAmount;
    }

    public void setTranAmount(String tranAmount) {
        this.tranAmount = tranAmount;
    }


    @Column(name = "settle_amount", length = 12)
    public String getSettleAmount() {
        return this.settleAmount;
    }

    public void setSettleAmount(String settleAmount) {
        this.settleAmount = settleAmount;
    }


    @Column(name = "card_holder_bill_amount", length = 12)
    public String getCardHolderBillAmount() {
        return this.cardHolderBillAmount;
    }

    public void setCardHolderBillAmount(String cardHolderBillAmount) {
        this.cardHolderBillAmount = cardHolderBillAmount;
    }


    @Column(name = "transmission_date", length = 10)
    public String getTransmissionDate() {
        return this.transmissionDate;
    }

    public void setTransmissionDate(String transmissionDate) {
        this.transmissionDate = transmissionDate;
    }


    @Column(name = "card_holder_billing_fee_amount", length = 8)
    public String getCardHolderBillingFeeAmount() {
        return this.cardHolderBillingFeeAmount;
    }

    public void setCardHolderBillingFeeAmount(String cardHolderBillingFeeAmount) {
        this.cardHolderBillingFeeAmount = cardHolderBillingFeeAmount;
    }


    @Column(name = "conversion_rate_settlement", length = 8)
    public String getConversionRateSettlement() {
        return this.conversionRateSettlement;
    }

    public void setConversionRateSettlement(String conversionRateSettlement) {
        this.conversionRateSettlement = conversionRateSettlement;
    }


    @Column(name = "conversion_rate_billing", length = 8)
    public String getConversionRateBilling() {
        return this.conversionRateBilling;
    }

    public void setConversionRateBilling(String conversionRateBilling) {
        this.conversionRateBilling = conversionRateBilling;
    }


    @Column(name = "trace_no", nullable = false, length = 6)
    public String getTraceNo() {
        return this.traceNo;
    }

    public void setTraceNo(String traceNo) {
        this.traceNo = traceNo;
    }


    @Column(name = "local_tran_time", length = 6)
    public String getLocalTranTime() {
        return this.localTranTime;
    }

    public void setLocalTranTime(String localTranTime) {
        this.localTranTime = localTranTime;
    }


    @Column(name = "local_tran_date", length = 4)
    public String getLocalTranDate() {
        return this.localTranDate;
    }

    public void setLocalTranDate(String localTranDate) {
        this.localTranDate = localTranDate;
    }


    @Column(name = "expire_date", length = 256)
    public String getExpireDate() {
        return this.expireDate;
    }

    public void setExpireDate(String expireDate) {
        this.expireDate = expireDate;
    }


    @Column(name = "settlement_date", length = 4)
    public String getSettlementDate() {
        return this.settlementDate;
    }

    public void setSettlementDate(String settlementDate) {
        this.settlementDate = settlementDate;
    }


    @Column(name = "currency_conversion_date", length = 4)
    public String getCurrencyConversionDate() {
        return this.currencyConversionDate;
    }

    public void setCurrencyConversionDate(String currencyConversionDate) {
        this.currencyConversionDate = currencyConversionDate;
    }


    @Column(name = "capture_date", length = 4)
    public String getCaptureDate() {
        return this.captureDate;
    }

    public void setCaptureDate(String captureDate) {
        this.captureDate = captureDate;
    }


    @Column(name = "merchant_type", length = 4)
    public String getMerchantType() {
        return this.merchantType;
    }

    public void setMerchantType(String merchantType) {
        this.merchantType = merchantType;
    }


    @Column(name = "acq_institute_country_code", length = 3)
    public String getAcqInstituteCountryCode() {
        return this.acqInstituteCountryCode;
    }

    public void setAcqInstituteCountryCode(String acqInstituteCountryCode) {
        this.acqInstituteCountryCode = acqInstituteCountryCode;
    }


    @Column(name = "pan_ext_country_code", length = 3)
    public String getPanExtCountryCode() {
        return this.panExtCountryCode;
    }

    public void setPanExtCountryCode(String panExtCountryCode) {
        this.panExtCountryCode = panExtCountryCode;
    }


    @Column(name = "fwd_institiute_country_code", length = 3)
    public String getFwdInstitiuteCountryCode() {
        return this.fwdInstitiuteCountryCode;
    }

    public void setFwdInstitiuteCountryCode(String fwdInstitiuteCountryCode) {
        this.fwdInstitiuteCountryCode = fwdInstitiuteCountryCode;
    }


    @Column(name = "entry_mode", length = 3)
    public String getEntryMode() {
        return this.entryMode;
    }

    public void setEntryMode(String entryMode) {
        this.entryMode = entryMode;
    }


    @Column(name = "pan_seq_no", length = 3)
    public String getPanSeqNo() {
        return this.panSeqNo;
    }

    public void setPanSeqNo(String panSeqNo) {
        this.panSeqNo = panSeqNo;
    }


    @Column(name = "nii", length = 3)
    public String getNii() {
        return this.nii;
    }

    public void setNii(String nii) {
        this.nii = nii;
    }


    @Column(name = "condition_code", length = 2)
    public String getConditionCode() {
        return this.conditionCode;
    }

    public void setConditionCode(String conditionCode) {
        this.conditionCode = conditionCode;
    }


    @Column(name = "capture_code", length = 2)
    public String getCaptureCode() {
        return this.captureCode;
    }

    public void setCaptureCode(String captureCode) {
        this.captureCode = captureCode;
    }


    @Column(name = "auth_id_length", length = 1)
    public String getAuthIdLength() {
        return this.authIdLength;
    }

    public void setAuthIdLength(String authIdLength) {
        this.authIdLength = authIdLength;
    }


    @Column(name = "tran_fee", length = 12)
    public String getTranFee() {
        return this.tranFee;
    }

    public void setTranFee(String tranFee) {
        this.tranFee = tranFee;
    }


    @Column(name = "settle_fee", length = 12)
    public String getSettleFee() {
        return this.settleFee;
    }

    public void setSettleFee(String settleFee) {
        this.settleFee = settleFee;
    }


    @Column(name = "tran_processing_fee", length = 12)
    public String getTranProcessingFee() {
        return this.tranProcessingFee;
    }

    public void setTranProcessingFee(String tranProcessingFee) {
        this.tranProcessingFee = tranProcessingFee;
    }


    @Column(name = "settlement_processing_fee", length = 12)
    public String getSettlementProcessingFee() {
        return this.settlementProcessingFee;
    }

    public void setSettlementProcessingFee(String settlementProcessingFee) {
        this.settlementProcessingFee = settlementProcessingFee;
    }


    @Column(name = "acq_institute_id_code", length = 14)
    public String getAcqInstituteIdCode() {
        return this.acqInstituteIdCode;
    }

    public void setAcqInstituteIdCode(String acqInstituteIdCode) {
        this.acqInstituteIdCode = acqInstituteIdCode;
    }


    @Column(name = "forward_institute_id_code", length = 14)
    public String getForwardInstituteIdCode() {
        return this.forwardInstituteIdCode;
    }

    public void setForwardInstituteIdCode(String forwardInstituteIdCode) {
        this.forwardInstituteIdCode = forwardInstituteIdCode;
    }


    @Column(name = "ext_pan", length = 30)
    public String getExtPan() {
        return this.extPan;
    }

    public void setExtPan(String extPan) {
        this.extPan = extPan;
    }


    @Column(name = "track_two_data", length = 256)
    public String getTrackTwoData() {
        return this.trackTwoData;
    }

    public void setTrackTwoData(String trackTwoData) {
        this.trackTwoData = trackTwoData;
    }


    @Column(name = "track_three_data", length = 110)
    public String getTrackThreeData() {
        return this.trackThreeData;
    }

    public void setTrackThreeData(String trackThreeData) {
        this.trackThreeData = trackThreeData;
    }


    @Column(name = "retreval_reference_no", length = 12)
    public String getRetrevalReferenceNo() {
        return this.retrevalReferenceNo;
    }

    public void setRetrevalReferenceNo(String retrevalReferenceNo) {
        this.retrevalReferenceNo = retrevalReferenceNo;
    }


    @Column(name = "auth_code", length = 6)
    public String getAuthCode() {
        return this.authCode;
    }

    public void setAuthCode(String authCode) {
        this.authCode = authCode;
    }


    @Column(name = "response_code", length = 3)
    public String getResponseCode() {
        return this.responseCode;
    }

    public void setResponseCode(String responseCode) {
        this.responseCode = responseCode;
    }


    @Column(name = "service_restriction_code", length = 3)
    public String getServiceRestrictionCode() {
        return this.serviceRestrictionCode;
    }

    public void setServiceRestrictionCode(String serviceRestrictionCode) {
        this.serviceRestrictionCode = serviceRestrictionCode;
    }


    @Column(name = "terminal_id", nullable = false, length = 8)
    public String getTerminalId() {
        return this.terminalId;
    }

    public void setTerminalId(String terminalId) {
        this.terminalId = terminalId;
    }


    @Column(name = "merchant_id", length = 15)
    public String getMerchantId() {
        return this.merchantId;
    }

    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId;
    }


    @Column(name = "card_acceptance_location", length = 40)
    public String getCardAcceptanceLocation() {
        return this.cardAcceptanceLocation;
    }

    public void setCardAcceptanceLocation(String cardAcceptanceLocation) {
        this.cardAcceptanceLocation = cardAcceptanceLocation;
    }


    @Column(name = "adnitional_response_data", length = 30)
    public String getAdnitionalResponseData() {
        return this.adnitionalResponseData;
    }

    public void setAdnitionalResponseData(String adnitionalResponseData) {
        this.adnitionalResponseData = adnitionalResponseData;
    }


    @Column(name = "field_46", length = 999)
    public String getField46() {
        return this.field46;
    }

    public void setField46(String field46) {
        this.field46 = field46;
    }


    @Column(name = "field_47", length = 999)
    public String getField47() {
        return this.field47;
    }

    public void setField47(String field47) {
        this.field47 = field47;
    }


    @Column(name = "field_48", length = 999)
    public String getField48() {
        return this.field48;
    }

    public void setField48(String field48) {
        this.field48 = field48;
    }


    @Column(name = "transaction_currency_code", length = 3)
    public String getTransactionCurrencyCode() {
        return this.transactionCurrencyCode;
    }

    public void setTransactionCurrencyCode(String transactionCurrencyCode) {
        this.transactionCurrencyCode = transactionCurrencyCode;
    }


    @Column(name = "track_one_data", length = 100)
    public String getTrackOneData() {
        return this.trackOneData;
    }

    public void setTrackOneData(String trackOneData) {
        this.trackOneData = trackOneData;
    }


    @Column(name = "settlement_currency_code", length = 3)
    public String getSettlementCurrencyCode() {
        return this.settlementCurrencyCode;
    }

    public void setSettlementCurrencyCode(String settlementCurrencyCode) {
        this.settlementCurrencyCode = settlementCurrencyCode;
    }


    @Column(name = "card_holder_billing_currency_code", length = 3)
    public String getCardHolderBillingCurrencyCode() {
        return this.cardHolderBillingCurrencyCode;
    }

    public void setCardHolderBillingCurrencyCode(String cardHolderBillingCurrencyCode) {
        this.cardHolderBillingCurrencyCode = cardHolderBillingCurrencyCode;
    }


    @Column(name = "sec_related_info", length = 16)
    public String getSecRelatedInfo() {
        return this.secRelatedInfo;
    }

    public void setSecRelatedInfo(String secRelatedInfo) {
        this.secRelatedInfo = secRelatedInfo;
    }


    @Column(name = "addition_amount", length = 125)
    public String getAdditionAmount() {
        return this.additionAmount;
    }

    public void setAdditionAmount(String additionAmount) {
        this.additionAmount = additionAmount;
    }


    @Column(name = "emv_data", length = 1024)
    public String getEmvData() {
        return this.emvData;
    }

    public void setEmvData(String emvData) {
        this.emvData = emvData;
    }


    @Column(name = "field_56", length = 999)
    public String getField56() {
        return this.field56;
    }

    public void setField56(String field56) {
        this.field56 = field56;
    }


    @Column(name = "field_57", length = 999)
    public String getField57() {
        return this.field57;
    }

    public void setField57(String field57) {
        this.field57 = field57;
    }


    @Column(name = "field_58", length = 59)
    public String getField58() {
        return this.field58;
    }

    public void setField58(String field58) {
        this.field58 = field58;
    }


    @Column(name = "field_59", length = 999)
    public String getField59() {
        return this.field59;
    }

    public void setField59(String field59) {
        this.field59 = field59;
    }


    @Column(name = "field_60", length = 999)
    public String getField60() {
        return this.field60;
    }

    public void setField60(String field60) {
        this.field60 = field60;
    }


    @Column(name = "field_61", length = 999)
    public String getField61() {
        return this.field61;
    }

    public void setField61(String field61) {
        this.field61 = field61;
    }


    @Column(name = "field_62", length = 999)
    public String getField62() {
        return this.field62;
    }

    public void setField62(String field62) {
        this.field62 = field62;
    }


    @Column(name = "field_63", length = 999)
    public String getField63() {
        return this.field63;
    }

    public void setField63(String field63) {
        this.field63 = field63;
    }


    @Column(name = "mac_data", length = 32)
    public String getMacData() {
        return this.macData;
    }

    public void setMacData(String macData) {
        this.macData = macData;
    }


    @Column(name = "settlement_status", nullable = false)
    public boolean isSettlementStatus() {
        return this.settlementStatus;
    }

    public void setSettlementStatus(boolean settlementStatus) {
        this.settlementStatus = settlementStatus;
    }


    @Column(name = "card_label", length = 100)
    public String getCardLabel() {
        return this.cardLabel;
    }

    public void setCardLabel(String cardLabel) {
        this.cardLabel = cardLabel;
    }


    @Column(name = "serial_number", nullable = false, length = 100)
    public String getSerialNumber() {
        return this.serialNumber;
    }

    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }


    @Column(name = "imei_number", nullable = false, length = 100)
    public String getImeiNumber() {
        return this.imeiNumber;
    }

    public void setImeiNumber(String imeiNumber) {
        this.imeiNumber = imeiNumber;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_at", nullable = false, length = 19)
    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_at", nullable = false, length = 19)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }


}


