package com.cba.core.wiremeweb.model;
// Generated Jun 20, 2023 2:49:48 PM by Hibernate Tools 4.3.1


import jakarta.persistence.*;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * TransactionCore generated by hbm2java
 */
@Entity
@Table(name = "transaction_core"
)
public class TransactionCore implements java.io.Serializable {

    private Integer id;
    private String originId;
    private String paymentMode;
    private String custMobile;
    private String tranType;
    private String cardLabel;
    private String terminalId;
    private Integer traceNo;
    private Integer invoiceNo;
    private int amount;
    private String currency;
    private Integer batchNo;
    private String pan;
    private Date dateTime;
    private String expDate;
    private String nii;
    private String rrn;
    private String authCode;
    private String signData;
    private Integer tipAmount;
    private String entryMode;
    private String dccCurrency;
    private Integer dccTranAmount;
    private Boolean issettled;
    private Integer settledMethod;
    private Date createdAt;
    private Date updatedAt;
    private String merchantId;
    private Set<SettlementInfo> settlementInfos = new HashSet<SettlementInfo>(0);

    public TransactionCore() {
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "origin_id", nullable = false, length = 65)
    public String getOriginId() {
        return this.originId;
    }

    public void setOriginId(String originId) {
        this.originId = originId;
    }

    @Column(name = "payment_mode", nullable = false, length = 10)
    public String getPaymentMode() {
        return this.paymentMode;
    }

    public void setPaymentMode(String paymentMode) {
        this.paymentMode = paymentMode;
    }

    @Column(name = "cust_mobile", length = 12)
    public String getCustMobile() {
        return this.custMobile;
    }

    public void setCustMobile(String custMobile) {
        this.custMobile = custMobile;
    }

    @Column(name = "tran_type", length = 10)
    public String getTranType() {
        return this.tranType;
    }

    public void setTranType(String tranType) {
        this.tranType = tranType;
    }

    @Column(name = "card_label", length = 20)
    public String getCardLabel() {
        return this.cardLabel;
    }

    public void setCardLabel(String cardLabel) {
        this.cardLabel = cardLabel;
    }

    @Column(name = "terminal_id", length = 9)
    public String getTerminalId() {
        return this.terminalId;
    }

    public void setTerminalId(String terminalId) {
        this.terminalId = terminalId;
    }

    @Column(name = "trace_no")
    public Integer getTraceNo() {
        return this.traceNo;
    }

    public void setTraceNo(Integer traceNo) {
        this.traceNo = traceNo;
    }

    @Column(name = "invoice_no")
    public Integer getInvoiceNo() {
        return this.invoiceNo;
    }

    public void setInvoiceNo(Integer invoiceNo) {
        this.invoiceNo = invoiceNo;
    }

    @Column(name = "amount", nullable = false)
    public int getAmount() {
        return this.amount;
    }

    public void setAmount(int amount) {
        this.amount = amount;
    }

    @Column(name = "currency", nullable = false, length = 6)
    public String getCurrency() {
        return this.currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    @Column(name = "batch_no")
    public Integer getBatchNo() {
        return this.batchNo;
    }

    public void setBatchNo(Integer batchNo) {
        this.batchNo = batchNo;
    }

    @Column(name = "pan", length = 25)
    public String getPan() {
        return this.pan;
    }

    public void setPan(String pan) {
        this.pan = pan;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date_time", nullable = false, length = 19)
    public Date getDateTime() {
        return this.dateTime;
    }

    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }

    @Column(name = "exp_date", length = 5)
    public String getExpDate() {
        return this.expDate;
    }

    public void setExpDate(String expDate) {
        this.expDate = expDate;
    }

    @Column(name = "nii", length = 5)
    public String getNii() {
        return this.nii;
    }

    public void setNii(String nii) {
        this.nii = nii;
    }

    @Column(name = "rrn", length = 20)
    public String getRrn() {
        return this.rrn;
    }

    public void setRrn(String rrn) {
        this.rrn = rrn;
    }

    @Column(name = "auth_code", length = 20)
    public String getAuthCode() {
        return this.authCode;
    }

    public void setAuthCode(String authCode) {
        this.authCode = authCode;
    }

    @Column(name = "sign_data", length = 10000)
    public String getSignData() {
        return this.signData;
    }

    public void setSignData(String signData) {
        this.signData = signData;
    }

    @Column(name = "tip_amount")
    public Integer getTipAmount() {
        return this.tipAmount;
    }

    public void setTipAmount(Integer tipAmount) {
        this.tipAmount = tipAmount;
    }

    @Column(name = "entry_mode")
    public String getEntryMode() {
        return this.entryMode;
    }

    public void setEntryMode(String entryMode) {
        this.entryMode = entryMode;
    }

    @Column(name = "dcc_currency")
    public String getDccCurrency() {
        return this.dccCurrency;
    }

    public void setDccCurrency(String dccCurrency) {
        this.dccCurrency = dccCurrency;
    }

    @Column(name = "dcc_tran_amount")
    public Integer getDccTranAmount() {
        return this.dccTranAmount;
    }

    public void setDccTranAmount(Integer dccTranAmount) {
        this.dccTranAmount = dccTranAmount;
    }

    @Column(name = "issettled")
    public Boolean getIssettled() {
        return this.issettled;
    }

    public void setIssettled(Boolean issettled) {
        this.issettled = issettled;
    }

    @Column(name = "settled_method")
    public Integer getSettledMethod() {
        return this.settledMethod;
    }

    public void setSettledMethod(Integer settledMethod) {
        this.settledMethod = settledMethod;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_at", nullable = false, length = 19)
    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_at", nullable = false, length = 19)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Column(name = "merchant_id", length = 16)
    public String getMerchantId() {
        return this.merchantId;
    }

    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "transactionCore")
    public Set<SettlementInfo> getSettlementInfos() {
        return this.settlementInfos;
    }

    public void setSettlementInfos(Set<SettlementInfo> settlementInfos) {
        this.settlementInfos = settlementInfos;
    }

}


