package com.cba.core.wiremeweb.model;
// Generated Jun 20, 2023 2:49:48 PM by Hibernate Tools 4.3.1


import java.util.Date;

import jakarta.persistence.*;


/**
 * UserConfig generated by hbm2java
 */
@Entity
@Table(name = "user_config"
)
public class UserConfig implements java.io.Serializable {


    private Integer id;
    private User user;
    private String configType;
    private String config;
    private Date createdAt;
    private Date updatedAt;

    public UserConfig() {
    }


    public UserConfig(String configType, Date createdAt, Date updatedAt) {
        this.configType = configType;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public UserConfig(User user, String configType, String config, Date createdAt, Date updatedAt) {
        this.user = user;
        this.configType = configType;
        this.config = config;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }


    @Column(name = "config_type", nullable = false, length = 20)
    public String getConfigType() {
        return this.configType;
    }

    public void setConfigType(String configType) {
        this.configType = configType;
    }


    @Column(name = "config", length = 65535, columnDefinition = "TEXT")
    public String getConfig() {
        return this.config;
    }

    public void setConfig(String config) {
        this.config = config;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_at", nullable = false, length = 19)
    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_at", nullable = false, length = 19)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }


}


