spring:
  messages:
    basename: messages
    encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 50
  datasource:
    url: jdbc:mysql://localhost:3306/haradb_new?serverTimezone=UTC&cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true
    username: root
    password: password
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: chanuucsc@gmail.com
    password: dlmfklwnyonycsta
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true # this should change to false when there is no SSL
            required: true
    protocol: smtp
    test-connection: false

application:
  jwt:
    secretKey: securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecure
    tokenPrefix: Bearer
    tokenExpirationAfterMillis: 84400000 # Token is issued for a Day, has to change once go live
  refresh:
    tokenExpirationAfterMillis: 120000
  resource:
    devices: devices

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

springdoc:
  api-docs:
    path: /swagger-doc
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    default-models-expand-depth: -1  # this is to remove unwanted tables view in swagger-ui

swagger:
  server:
    url: http://localhost:8091/wireme-coreweb

# this is to activate spring actuator
management:
  endpoints:
    web:
      exposure:
        include: httpexchanges,health,info,metrics,env,loggers
    enabled-by-default: true

logging:
  config: C:\conf\wiremecoreweb\logback-spring.xml