spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: chanuucsc@gmail.com
    password: dlmfklwnyonycsta
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp
    test-connection: false

application:
  jwt:
    secretKey: securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecure
    tokenPrefix: Bearer
    tokenExpirationAfterMillis: 84400000
  refresh:
    tokenExpirationAfterMillis: 120000

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

springdoc:
  api-docs:
    path: /swagger-doc
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    default-models-expand-depth: -1

swagger:
  server:
    url: http://123.231.95.112:8091/wireme-coreweb

management:
  endpoints:
    web:
      exposure:
        include: httpexchanges,health,info,metrics,env,loggers
    enabled-by-default: true

logging:
  config: /opt/conf/wiremecoreweb/logback-spring.xml